#!/usr/bin/env bash
set -e

processed_args=()
for arg in "$@"; do
  # automatically add "@_global_" syntax where needed
  if [[ $arg =~ ^(database|evolution|task|cluster|variant)=([^@].*)$ ]]; then
    key=${BASH_REMATCH[1]}
    val=${BASH_REMATCH[2]}
    processed_args+=("${key}@_global_=${val}")
  else
    processed_args+=("$arg")
  fi
done

python -m cuco.launch_hydra "${processed_args[@]}"
